//COMMENTS FLAG TEST (KABANGA)
###
POST http://localhost:8081/commentFlags/add
Content-Type: application/json 

{
    "commentId" : "69a1d941b3d6ddcab5fb852c",
    "reviewStatus" : "pending"
}

###
GET http://localhost:8081/commentFlags/getAll
Content-Type: application/json