//COMMENTS FLAG TEST (KABANGA)
###
POST http://localhost:8081/commentFlags/add
Content-Type: application/json 

{
    "commentId" : "69dfbb5fa35ea01f9742e935",
    "reviewStatus" : "pending"
}

###
GET http://localhost:8081/commentFlags/getAll
Content-Type: application/json