//COMMENTS FLAG TEST (KABANGA)
###
POST http://localhost:8081/commentFlags/add
Content-Type: application/json 

{
    "commentId" : "635ab8dfc407faf9f73deaf2",
    "reviewStatus" : "pending"
}

###
GET http://localhost:8081/commentFlags/getAll
Content-Type: application/json